### ISSUE TITLE
Enable calculation of FOGGIE spectra with "cgm" regions folded in

### ISSUE THREAD

**Issue by tumlinson** [foggie-sims/foggie#10]
Need to be able to compute spectra with region="cgm", "cool cgm", etc with associated bookkeeping. Important for kinematic analysis of cool/warm CGM, including velocity dispersion and doppler b values.

**Comment by tumlinson** [comment]
It did. Let's close.

**Comment by brittonsmith** [comment]
Added in trident [PR #91](https://github.com/trident-project/trident/pull/91).
